before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: DavidWittman
      name: ec2-dnsspy
    folder: Formula
    homepage: https://github.com/DavidWittman/ec2-dnsspy
    description: 🕵 Spy on DNS requests for your EC2 instances in (almost) real time 
