# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2Dnsspy < Formula
  desc "🕵 Spy on DNS requests for your EC2 instances in (almost) real time"
  homepage "https://github.com/DavidWittman/ec2-dnsspy"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DavidWittman/ec2-dnsspy/releases/download/v0.0.1/ec2-dnsspy_0.0.1_Darwin_arm64.tar.gz"
      sha256 "797d6cad5bd7eec09b758fab32642f17a722bd62de97eea0893294bac522ff10"

      def install
        bin.install "ec2-dnsspy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DavidWittman/ec2-dnsspy/releases/download/v0.0.1/ec2-dnsspy_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "72aaa7cdd25812aec192d731056f5b3c03c1851ba87dd5c6244ae1fa0311a59d"

      def install
        bin.install "ec2-dnsspy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DavidWittman/ec2-dnsspy/releases/download/v0.0.1/ec2-dnsspy_0.0.1_Linux_arm64.tar.gz"
      sha256 "3ca10864250e314dceaff2bc4b37393663f482ec3dca38384cadd04db5f1a2e3"

      def install
        bin.install "ec2-dnsspy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DavidWittman/ec2-dnsspy/releases/download/v0.0.1/ec2-dnsspy_0.0.1_Linux_x86_64.tar.gz"
      sha256 "6329827cb06c5d31b2402197419023705db06e80d80bbd8a96072c340e20f6bb"

      def install
        bin.install "ec2-dnsspy"
      end
    end
  end
end
